#ifndef CONST_H_INCLUDED
#define CONST_H_INCLUDED

#define WINDOW_SIZE 640
#define FRAME_LIMIT 60
#define TILE_SIZE 32
#define N_TILES_IN_MAP 200
#define SPRITE_WIDTH 16
#define SPRITE_HEIGHT 62
#define PLAYER_SPEED_FACTOR 0.4


#endif // CONST_H_INCLUDED
