#ifndef CONST_H_INCLUDED
#define CONST_H_INCLUDED

#define PI 3.14159265

#define WINDOW_SIZE 640
#define FRAME_LIMIT 60
#define TILE_SIZE 32
#define N_TILES_IN_MAP 200
#define SPRITE_WIDTH 16
#define SPRITE_HEIGHT 62

#define LEVEL_CAP 30
#define PLAYER_SPEED_FACTOR 0.4
#define MAGIC_ATTACK_ICREMENT 2
#define COOLDOWN_TIME_DECREMENT 0.9

#define PROJECTILE_ATTACK 3
#define PROJECTILE_SPEED 3
#define PROJECTILE_TIME 100
#define PROJECTILE_COOLDOWN 60
#define PROJECTILE_AOE 0

#define FIREBALL_ATTACK 2
#define FIREBALL_SPEED 4
#define FIREBALL_TIME 100
#define FIREBALL_COOLDOWN 200
#define FIREBALL_AOE 40

#define BUG_EXP 10
#define BUG_MONSTER_AREA_X 1000
#define BUG_MONSTER_AREA_Y 1000
#define BUG_MONSTER_X 300
#define BUG_MONSTER_Y 100
#define NUMBER_OF_BUG_MONSTERS 30
#define SPAWN_TIME_OF_BUG_MONSTERS 10



#endif // CONST_H_INCLUDED
